version: '3'

services:
  db:
    image: postgres:10.9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secrect
      - POSTGRES_USER=postgres
    command: postgres -c wal_level=logical -c max_replication_slots=1
  redis:
    image: redis:4.0.9
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:7.9.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    

volumes:
  esdata:
