version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.9.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    

volumes:
  esdata:
